"""empty message

Revision ID: 60a865ee9397
Revises: None
Create Date: 2016-03-26 11:34:39.105622

"""

# revision identifiers, used by Alembic.
revision = '60a865ee9397'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('nombre_usuario', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('clave', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nombre_usuario')
    )
    op.create_table('amigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('amigo1', sa.String(), nullable=True),
    sa.Column('amigo2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['amigo1'], ['usuario.nombre_usuario'], ),
    sa.ForeignKeyConstraint(['amigo2'], ['usuario.nombre_usuario'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_admin', sa.String(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['id_admin'], ['usuario.nombre_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_origen', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['usuario_origen'], ['usuario.nombre_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagina',
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.nombre_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('miembrosGrupo',
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['grupo'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.nombre_usuario'], ),
    sa.PrimaryKeyConstraint('grupo', 'usuario')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miembrosGrupo')
    op.drop_table('pagina')
    op.drop_table('mensaje')
    op.drop_table('grupo')
    op.drop_table('amigo')
    op.drop_table('usuario')
    op.drop_table('chat')
    ### end Alembic commands ###
